### ISSUE TITLE
Failed to register operators for plugin @voxel51/io

### ISSUE THREAD

**Issue by msy1412** [voxel51/fiftyone-plugins#70]
I checked the operation of the io plugin with command "fiftyone operators list", but got "Failed to register operators for plugin @voxel51/io".

**Comment by msy1412** [comment]
There is some error information showed in App:

Error loading python plugins

Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Python\Python39\site-packages\fiftyone\operators\loader.py", line 125, in register_all
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\...\fiftyone\__plugins__\@voxel51\io\__init__.py", line 14, in <module>
    import fiftyone.core.storage as fos
ModuleNotFoundError: No module named 'fiftyone.core.storage'
-------------------------------------------------------------------------------------------------------------------------
I fixed it by upgrading fiftyone: pip install --upgrade fiftyone fiftyone-brain fiftyone-db fiftyone-desktop
